author: Tobe O <thosakwe@gmail.com>
description: Material sidenav for Angular2.
environment:
  sdk: ">=1.23.0-beta"
homepage: https://github.com/thosakwe/material_sidenav.git
name: material_sidenav
version: 2.0.0
dependencies: 
  angular2: ">=3.0.0-beta <4.0.0"
dev_dependencies: 
  angular_components: ">=0.5.0-beta <2.0.0"
  browser: ^0.10.0
  material_menu: ^2.0.0
  material_toolbar: ^2.0.0
transformers:
- angular2: 
    entry_points: web/main.dart
    platform_directives: 
      - package:angular2/common.dart#COMMON_DIRECTIVES
    platform_pipes: 
      - package:angular2/common.dart#COMMON_PIPES