author: "Tobe O <thosakwe@gmail.com>"
description: "Material sidenav for Angular2."
homepage: "https://github.com/thosakwe/material_sidenav.git"
name: "material_sidenav"
version: "1.0.0"
dependencies: 
  angular2: "^2.2.0"
dev_dependencies: 
  angular2_components: "^0.2.1"
  browser: "^0.10.0+2"
  material_menu: "^1.0.0+1"
  material_toolbar: "^1.0.0"
transformers:
- angular2: 
    entry_points: "web/main.dart"
    platform_directives: 
      - "package:angular2/common.dart#COMMON_DIRECTIVES"
    platform_pipes: 
      - "package:angular2/common.dart#COMMON_PIPES"